name: Enforce PR Merge Order

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check_previous_prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get open PRs
        uses: actions/github-script@v6
        id: get-prs
        with:
          script: |
            const { data: prs } = await github.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              sort: 'created',
              direction: 'asc'
            });
            return prs;

      - name: Check if any older PRs exist
        run: |
          echo "Checking PRs..."
          if [ $(jq length <<< "${{ steps.get-prs.outputs.result }}") -gt 0 ]; then
            echo "There are older PRs that need to be merged first."
            exit 1
          fi
        shell: bash
