name: Enforce PR Merge Order

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check_previous_prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get open PRs
        id: get-prs
        run: |
          echo "Getting open pull requests..."
          prs=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/pulls?state=open&sort=created&direction=asc")
          echo "$prs" > prs.json
          echo "::set-output name=result::$(jq -c . prs.json)"

      - name: Check if any older PRs exist
        run: |
          echo "Checking PRs..."
          if [ $(jq length <<< "${{ steps.get-prs.outputs.result }}") -gt 0 ]; then
            echo "There are older PRs that need to be merged first."
            exit 1
          fi
        shell: bash
